[project]
name = "codecademy-dsa-python"
version = "0.1.0"
description = "data structures and algorithms course from codecademy"

readme = "README.md"

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.8",
    "uv>=0.4.17",
]
